### ISSUE TITLE
Conform to a more typical file structure

### ISSUE THREAD

**Issue by davenuman** [davenuman/bowline#11]
The existing file layout simply ended up the way it is during initial development. After review, it would be sensible to clean things up and follow a more expected organization.

Here is a draft new file layout:

```
bin/activate # Replaces scripts/include.bash. Have it alter PS1 and PATH, and add deactivate alias
bin/build # Just build on it's own
bin/import # Does what "build import" does now
bin/run # Run tests
bin/sync-db # Sync DB
lib/bowline/bowline
```
This would allow for project specific scripts to be added as `bin/foo` and such.

The scripts in `bin` would make use of functions located in `lib/bowline/bowline`. Code within scripts/build and scripts/run would be re-factored into this file as functions. The `lib/bowline` part could then be non-project customizable, and hence upgradable.

(Thanks @grugnog for suggesting these changes.)

**Comment by openprivacy** [comment]
Some thoughts:
1. It will get messy with bowline standard and locally created 'bin' scripts in the same directory.
2. It would be nice to be able to add pre- and post-hooks to the scripts to perform additional site-specific customization, for example:
 - import-post-hook could run reload-config after the import
 - run-pre-hook could ensure local.yml has been updated with local paths & IP addresses

3. I like 'scripts' better than 'bin' as I think of 'bin' for binaries (but maybe I'm just old-fashioned here)
4. If you went with all these suggestions, it might be good to put everything in a sub-directory

So I might have:
* `bowline/scripts/build`
* `bowline/lib/`
* `bowline/local/hooks/      # bowline/local is .gitignored by bowline...`
* `bowline/local/scripts/     # ...and provided by the local project.`
* `scripts/                          # not part of bowline`

There could be a script `bowline/scripts/refresh-scripts` that symlinks all the `bowline/scripts/*` and `bowline/local/scripts/*` files into the top-level `scripts` directory...

**Comment by davenuman** [comment]
I think the question is, what is the most likely place that people will be looking for these files. I like the idea of a bowline directory however i don't think it's readily obvious of what might be in it. That's why lib/bowline sounds good to me.

**Comment by davenuman** [comment]
p.s. I love the idea of adding hooks as well. (Possibly for a new issue though)

**Comment by openprivacy** [comment]
From offline discussion, agree that:
* bin/ rules
* local/ should not exist
* hooks are cool

**Comment by kostajh** [comment]
@davenuman one suggestion would be to submit this as a project to Packagist and reimplement the script commands as a PHP command (e.g. `bowline import`). That way one could require this project via Composer.

**Comment by davenuman** [comment]
@kostajh I've considered that but one of my primary goals of Bowline is to minimize requirements. That strategy would require php and composer to be installed. I know it's not too hard to install those but it does add some steps.

**Comment by kostajh** [comment]
@davenuman true. But it does handle the installation / updates of this package in a more or less standardized way. As an aside I don't think the script commands would even need to be rewritten in PHP. But yes, folks would have to install composer.

**Comment by kostajh** [comment]
Actually, you wouldn't need to use composer if you didn't want to (e.g. if you wanted to use the current README suggestions for usage).

**Comment by davenuman** [comment]
I'd like to merge in my changes in the reorganize branch even though it may have some broken or missing pieces.

I don't know if anyone is using this project much, but if you need the previous layout for some reason, here is the last commit with it: 1f2d250
