### ISSUE TITLE
Error on activate

### ISSUE THREAD

**Issue by petertornstrand** [davenuman/bowline#13]
I'm getting the following error when running `. bin/activate`:

    bowline_init:export:19: not valid in this context: db:\nweb
    Bowline activated. Enter 'bowline' command to get started.

When running the `bowline` command I'm getting:

    zsh: command not found: bowline

Also, my prompt looks like this:

    $ \[\033[01;31m\]()\[\033[00m\] $

**Comment by davenuman** [comment]
hi @petertornstrand
I see you are using zsh from the "command not found" error.  I haven't tested at all using that. The bowline project is heavily built on bash.

As a work-around, try activating like this:
```bash
bash
. bin/activate
```
This will put you in a bash session first.

Not sure what the long term fix is. I know a lot of people use zsh.

**Comment by davenuman** [comment]
@petertornstrand
I installed zsh to reproduce the errors, and moved some code around to solve it. It works for me now in zsh.

The activate script attempts to indicate that bowline is activated by adding to the shell prompt. In bash this shows up as red with the project name. I have it added in zsh but it doesn't stand out as much. Here is the line that adds it:
https://github.com/davenuman/bowline/blob/master/bin/activate#L24
If you have ideas on how to make it stronger, I welcome pull requests.

**Comment by davenuman** [comment]
I assume my fix resolved this issue. Please re-open if it's still not working on latest master branch.

**Comment by petertornstrand** [comment]
Thank you @davenuman . I haven't tested it yet but I'm sure that solves it.
