### ISSUE TITLE
Make updating a bit easier

### ISSUE THREAD

**Issue by kostajh** [davenuman/bowline#17]
Well, updating is pretty easy. But there's a few steps I have to do each time:

``` bash
git rm -f LICENSE.md sandbox.md readme.md
git reset .gitignore
git checkout -- .gitignore
```

And then, manually verify the `composer.json` changes (if any).

I don't know what a reasonable workaround for this might look like, but just putting this out there.

**Comment by davenuman** [comment]
This is an important question for this project as it's not a typical clone situation, more of a boilerplate/starter code for a project in a different repo.

Currently I'm using a different approach from what you're doing, going the other way around:
```
git remote update
git checkout bowline/master -- bin lib
```
This assumes bowline is set up as a second remote named `bowline`. I imagine composer.json and the other files in the project root wouldn't need updating really. Especially composer as that would quickly become project specific. (I recently striped down composer.json to a bare minimum to allow projects to only require what they need.)

This process could definitely use some refinement. I think the `lib` directory provides a clean area for Bowline updates and maybe `bin`, but everything else gets uncertain. Wondering if an update script would be helpful. I'm open to suggestions.

**Comment by kostajh** [comment]
@davenuman `git checkout bowline/master -- bin lib` worked great! Maybe just add a "How to update" section to the README with those lines?

**Comment by davenuman** [comment]
https://github.com/davenuman/bowline#updating-bowline
