### ISSUE TITLE
How to use the reverse proxy

### ISSUE THREAD

**Issue by vekexasia** [davenuman/bowline#18]
Hello,

i'm trying to understand how to use the reverse proxy but i didn't quite get it.

Can you help me and explain how to use it ?

**Comment by davenuman** [comment]
I just recently added this to the readme: https://github.com/davenuman/bowline#docker-subnet-proxy-for-nice-urls
Does that aswer your question?
One thing I just thought of is that it assumes you don't have anything using port 80. Running `invoke_proxy` will fail if you already have something on port 80 docker or otherwise.

**Comment by vekexasia** [comment]
Hello dave,

I indeed followed those instructions but i don't understand how to use it. I mean, I've the following containers running:
```
301a199039bd        proxy_dnsmasq:latest               "/usr/sbin/dnsmasq -   12 hours ago        Up 12 hours         53/tcp              proxy_dnsmasq_1          
2b1e6640b833        davenuman/bowline-web-php:latest   "/start.sh"            12 hours ago        Up 12 hours         80/tcp              ristorantidrupal_web_1   
aa88ebef53b0        mysql:5.5                          "/entrypoint.sh mysq   12 hours ago        Up 12 hours         3306/tcp            ristorantidrupal_db_1 
```

No nginx. Furthermore, i don't see how to use the domain name in my pc to access the container instead of using the ip directly. Is there something i need to configure on my pc to use the dnsmasq in order to resolve projectname.localtest.me?

**Comment by davenuman** [comment]
projectname.localtest.me should resolve to 127.0.0.1 and the nginx docker container should be using port 80 on your localhost.


When I do `docker ps | grep proxy` i see this:
```
790e4b8bb157        nginx:latest                       "nginx -g 'daemon of   2 days ago          Up 2 days           443/tcp, 0.0.0.0:80->80/tcp     proxy_nginx_1
485c08dba5a1        proxy_dnsmasq:latest               "/usr/sbin/dnsmasq -   2 days ago          Up 2 days           53/tcp                          proxy_dnsmasq_1
```

If nginx isn't running check the logs with `docker logs proxy_nginx_1`. I think the likely reason is that port 80 is already in use so it quits. Another way to check is to restart and see if there are helpful error message:
```bash
fig -f lib/proxy/fig.yml stop
fig -f lib/proxy/fig.yml start
```
If you do have something on port 80 (LAMP or MAMP, etc) then either stop that service or edit the `lib/proxy/fig.yml` file and change `80:80` to `8080:80` or such and try again.

**Comment by davenuman** [comment]
ps. if you do edit the lib/proxy/fig.yml file then the url projectname.localtest.me:8080 or whatever port you set in the config.
