### ISSUE TITLE
Curiosity, Why did you call it bowline?

### ISSUE THREAD

**Issue by vekexasia** [davenuman/bowline#21]
Hello,

i'm curious about the name. I'm planning to do a similar project but for wordpress.

**Comment by davenuman** [comment]
I was thinking along the lines of nautical terms and shipping. Docker uses the shipping container metaphore. I used to go sailing (and hope to again) and have tied many bowline knots, tying halyards to sails, etc. Of course sailboats don't directly connect with shipping containers but i suspect the crew of those big freighters also know how to tie bowlines.

**Comment by davenuman** [comment]
Also, a bowline is a handy knot, easy to tie and untie, useful in many situations. Hoping this project might become such.

**Comment by vekexasia** [comment]
Nice to know. I'm trying to create some kind of fork for wordpress here: https://github.com/vekexasia/bowline-for-wordpress

**Comment by davenuman** [comment]
Cool. Makes sense as WP and Drupal use a very similar stack. Good luck!
