### ISSUE TITLE
Not working on Fedora 21

### ISSUE THREAD

**Issue by kostajh** [davenuman/bowline#4]
Hi @davenuman,

I might be doing something wrong. I'm trying the instructions for a new project in the README, and getting these errors:

``` bash
$ sudo bash scripts/build init
Error: No such image or container: myproject_web_1
```

And then:

``` bash
$ sudo bash scripts/build 
Error: No such image or container: myproject_web_1
# BUILDING CONTAINERS
Building without importing database. (Run as './scripts/build import' if you need to load the db.)
scripts/build: line 56: fig: command not found
scripts/build: line 57: fig: command not found
FATA[0000] Error response from daemon: No such container: composer 
FATA[0000] Error response from daemon: No such container: composer 
docker: "exec" requires a minimum of 2 arguments. See 'docker exec --help'.
scripts/build: line 69: fig: command not found
docker: "inspect" requires a minimum of 1 argument. See 'docker inspect --help'.
docker: "inspect" requires a minimum of 1 argument. See 'docker inspect --help'.
# Fig/docker container status
scripts/build: line 74: fig: command not found

# BUILD COMPLETE
database IP: ; web IP: 
web address: http:///

  If the above link does not work and you are using Boot2Docker,
  run the following command then try the link again.
      sudo route -n add 172.17.0.0/16 192.168.59.103
```

Any ideas? I have `fig` 1.0.1 installed locally via `pip install fig --user`.

**Comment by kostajh** [comment]
And for what it's worth, I followed the instructions for setting up Docker here https://docs.docker.com/installation/fedora/#starting-the-docker-daemon, and verified that `sudo docker run -i -t fedora /bin/bash` works.

**Comment by davenuman** [comment]
Hi @kostajh 
I haven't tried on fedora. Not sure what's going wrong but the "fig: command not found" is the main problem. Make sure you have fig available in the command line. Perhaps you need to specify the absolute path to fig (output of "which fig") in the include.bash here:
https://github.com/davenuman/bowline/blob/master/scripts/include.bash#L8

**Comment by kostajh** [comment]
@davenuman `which fig` yields `~/.local/bin/fig` and in my bashrc, I've got `export PATH=$HOME/.local/bin:$PATH`

I'll experiment a bit and see what I can come up with. Thanks for your help, I'm excited to use this project!

**Comment by kostajh** [comment]
@davenuman so, I tried the other install method and downloaded the bin from https://github.com/docker/fig/releases/tag/1.0.1, and moved to `/usr/local/bin/fig`. Still getting the `fig: command not found` error. I see that Fig says to install `boot2docker` on OS X and Windows, but do I need to use that?

**Comment by davenuman** [comment]
What happens when you just run `./scripts/build`? I didn't notice at first that you are using `sudo`. I have my docker set up so that i can run it without sudo. (That may actually be a requirement that i need to add to the readme.)

**Comment by kostajh** [comment]
@davenuman looks like the problem was with `boot2docker` missing, but I'll let you know soon. I'll provide some notes for the README if that's the case.

**Comment by davenuman** [comment]
Afaik, boot2docker is only needed if you are on Mac or Windows. I use linux and I don't have boot2docker installed.

**Comment by davenuman** [comment]
Also, I'm still using fig as docker-compose isn't as widely adopted on all distros yet, as far as i can tell.

**Comment by kostajh** [comment]
@davenuman so, I followed the instructions for Fedora to allow running `docker` without sudo.

Here's the output of `./scripts/build`:
```
# BUILDING CONTAINERS
Building without importing database. (Run as './scripts/build import' if you need to load the db.)
Starting bowline_web_1...
FATA[0000] Error response from daemon: Container bowline_web_1 is not running 
FATA[0000] Error response from daemon: Container bowline_web_1 is not running 
FATA[0000] Error response from daemon: Container bowline_web_1 is not running 
# Fig/docker container status
    Name               Command          State     Ports   
---------------------------------------------------------
bowline_db_1    /entrypoint.sh mysqld   Up       3306/tcp 
bowline_web_1   /start.sh               Exit 1            

# BUILD COMPLETE
database IP: 172.17.0.4; web IP: 
web address: http:///

  If the above link does not work and you are using Boot2Docker,
  run the following command then try the link again.
      sudo route -n add 172.17.0.0/16 192.168.59.103
```

**Comment by davenuman** [comment]
Looks like what i get. That reminds me that the `FATA[0000] Error response from daemon: Container bowline_web_1 is not running` message is not a problem there. I need to add a check so that doesn't happen.

**Comment by davenuman** [comment]
Ooops, I read that too quickly. I see you have a missing IP for the web address Something's not right. I'll try to reproduce that here.

**Comment by kostajh** [comment]
@davenuman yeah, and if I do `docker ps` I see the mysql container running, but not the web one. Are you on Debian?

**Comment by kostajh** [comment]
@davenuman fwiw I'm totally new to Docker, so more than likely this is an issue w/ my set up. Just as some more info, I can run the tests on https://github.com/alberto56/realistic_dummy_content successfully, so I know Docker is working at least in some contexts.

**Comment by davenuman** [comment]
I'm running arch locally. I also have bowline working on an ubuntu ci server, and some coworkers have it running on osx.

**Comment by kostajh** [comment]
@davenuman after rebooting, I get different errors:

``` bash
$ bash scripts/build 
An error occurred trying to connect: Get https://192.168.59.104:2376/v1.17/images/bowline_web_1/json: dial tcp 192.168.59.104:2376: no route to host# BUILDING CONTAINERS
Building without importing database. (Run as './scripts/build import' if you need to load the db.)
Couldn't connect to Docker daemon at https://192.168.59.104:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Couldn't connect to Docker daemon at https://192.168.59.104:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
FATA[0002] An error occurred trying to connect: Post https://192.168.59.104:2376/v1.17/containers/composer/exec: dial tcp 192.168.59.104:2376: no route to host 
FATA[0003] An error occurred trying to connect: Post https://192.168.59.104:2376/v1.17/containers/composer/exec: dial tcp 192.168.59.104:2376: no route to host 
docker: "exec" requires a minimum of 2 arguments. See 'docker exec --help'.
Couldn't connect to Docker daemon at https://192.168.59.104:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
docker: "inspect" requires a minimum of 1 argument. See 'docker inspect --help'.
docker: "inspect" requires a minimum of 1 argument. See 'docker inspect --help'.
# Fig/docker container status
Couldn't connect to Docker daemon at https://192.168.59.104:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

# BUILD COMPLETE
database IP: ; web IP: 
web address: http:///

  If the above link does not work and you are using Boot2Docker,
  run the following command then try the link again.
      sudo route -n add 172.17.0.0/16 192.168.59.103
```

If I run `sudo bash scripts/build` I get the `fig: command not found` errors.

**Comment by davenuman** [comment]
`Couldn't connect to Docker daemon at https://192.168.59.104:2376 - is it running?`
Sounds like docker didn't start after reboot

**Comment by kostajh** [comment]
Yeah, it's running:

``` bash
$ sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
   Active: active (running) since Tue 2015-02-24 14:10:38 EST; 35min ago
     Docs: http://docs.docker.com
 Main PID: 3536 (docker)
   CGroup: /system.slice/docker.service
           ├─3536 /usr/bin/docker -d --selinux-enabled
           └─8564 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.5 -container-port 80

Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="-job containers() = OK (0)"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="GET /v1.12/containers/json?all=0&limit=-1&trunc_cmd=1&size=0"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="+job containers()"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="-job containers() = OK (0)"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="GET /v1.12/containers/4dff9cf7b27d47a3b837d5c22991273c08ee386fbe71dbae81cdb15c48667d64/json"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="+job container_inspect(4dff9cf7b27d47a3b837d5c22991273c08ee386fbe71dbae81cdb15c48667d64)"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="-job container_inspect(4dff9cf7b27d47a3b837d5c22991273c08ee386fbe71dbae81cdb15c48667d64) = OK (0)"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="GET /v1.12/containers/5b5e89b863c6e85cec821bfff8c032ee065fb6bdf359a402bd0147acbb074359/json"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="+job container_inspect(5b5e89b863c6e85cec821bfff8c032ee065fb6bdf359a402bd0147acbb074359)"
Feb 24 14:39:05 kafes docker[3536]: time="2015-02-24T14:39:05-05:00" level="info" msg="-job container_inspect(5b5e89b863c6e85cec821bfff8c032ee065fb6bdf359a402bd0147acbb074359) = OK (0)"
```

**Comment by davenuman** [comment]
It might be good to verify fig is working. Something like this: 
Create a new directory with a new file called fig.yml containing this:
```
web:
  image: debian:wheezy
  command: sleep 60
```

then in that dir, run this:
```
fig up -d
fig ps
```

**Comment by davenuman** [comment]
Also, I'm noticing the ip in your error: `FATA[0002] An error occurred trying to connect: Post https://192.168.59.104 [...]`  isn't the same subnet as the `172.17.0.5` container ip in the `service docker status` output.  I've seen that docker uses different subnets (192..., 172...) on different platoforms but it's strage to see this mixture on the same machine. Something to google for perhaps. Also, double check that `docker ps` still works.

**Comment by kostajh** [comment]
@davenuman thanks for the suggestions.

``` bash
$ sudo fig up -d
Creating tes_web_1...
Pulling image debian:wheezy...
30d39e59ffe2: Already exists
c90d655b99b2: Already exists
debian:wheezy: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Image is up to date for debian:wheezy
```
and
``` bash
  $ sudo fig ps
  Name       Command    State   Ports 
-------------------------------------
tes_web_1   sleep 606   Up  
```

In my usage of the other repo I mentioned above, it looks like docker is only working properly with `sudo`, even though I did [as suggested](https://docs.docker.com/installation/fedora/) and added my user to a docker group.

So, possibly it's something related to the build script that is expecting it to not be run with sudo.

**Comment by kostajh** [comment]
Also, `docker ps` results in `network is unreachable` but `sudo docker ps` works fine.

**Comment by kostajh** [comment]
@davenuman I ran `sudo fig up -d` in the root of the repo. I see both containers for web and db are created, but web fails with Exit 1. `sudo fig logs` shows:

```
Attaching to bowline_web_1, bowline_db_1
web_1 | mkdir: cannot create directory `/var/www/docroot/sites/default/files': Permission denied
web_1 | mkdir: cannot create directory `/var/www/logs': Permission denied
web_1 | mkdir: cannot create directory `/var/www/files-private': Permission denied
```

So I think this is a SELinux issue actually. I'll report back when I figure it out.

**Comment by davenuman** [comment]
Come to think of it, running docker as your own user is a requirement for bowline. Some of the user permissions tricks that it does would be useless if run with sudo. Bowline tried to make sure all the files in the project are owned but the user for easy editing and such. (I'll need to update the readme on this requirement.)

**Comment by kostajh** [comment]
@davenuman that makes sense. I'll try to get docker/fig working without sudo then come back to this project.

**Comment by kostajh** [comment]
@davenuman success! The two key things are (1) don't run this script using sudo and (2) set SELinux to `permissive` or be on top of the errors generated if you have SELinux set to `enforcing`. Would you like a PR with some notes about these things?

**Comment by davenuman** [comment]
@kostajh
I dropped the ball on this. Yes, I would like a PR with notes as you suggest. I've already added mention of the requirement to run without sudo: https://github.com/davenuman/bowline/blob/master/readme.md#requirements
