### ISSUE TITLE
fig is now called docker-compose

### ISSUE THREAD

**Issue by kostajh** [davenuman/bowline#5]
I saw this when investigating #4, just FYI: https://github.com/docker/fig/releases

**Comment by davenuman** [comment]
I've heard of this shift of fig into docker, but I don't see it widely available yet in the packages. I couldn't get it to work easily in arch Linux anyway. Fig send to still be the stable approach for now.

**Comment by davenuman** [comment]
Feel free to reopen this with a link to documentation on stable docker-compose. I haven't found such at this point.

**Comment by kostajh** [comment]
@davenuman I ran across it here: https://github.com/docker/fig/releases . Looks like will it be part of release 1.1.0

**Comment by davenuman** [comment]
Yes, I've seen that too and I'm trying to keep up with the fast moving docker community. However I don't see docker compose available yet in latest release. I'm using docker 1.5.0. I'm expecting something on the docs page eventually: https://docs.docker.com/jsearch/?q=compose

> The command you type is now docker-compose, not fig.

```
docker-compose
-bash: docker-compose: command not found
```

**Comment by davenuman** [comment]
Also, the github page for docker-compose  https://github.com/docker/fig still links to fig.sh at the bottom for install instructions.

**Comment by kostajh** [comment]
OK, cool. So, let's keep this issue closed for now :-)

**Comment by thinhduckhoi** [comment]
God! Did anyone solve this problem?
