### ISSUE TITLE
Make SQL backup configurable

### ISSUE THREAD

**Issue by kostajh** [davenuman/bowline#8]
I'm working on a project now with a 2 GB SQL DB, and would prefer not to have it backed up before running `./scripts/build import`. It would be nice to have a flag like `--no-backup` to skip doing a DB dump. I know I can configure this on a per project basis, but wondering if you think this is good to have in the main project.

**Comment by davenuman** [comment]
added in this commit: dfdf9b3738b39f5a9ab2b7d6ce68cd8d2ee4629c
